---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          rfc2136:
            nameserver: bind9.network.svc.cluster.local:53
            tsigKeyName: cm-acme
            tsigAlgorithm: HMACSHA512
            tsigSecretSecretRef:
              name: bind9-tsig
              key: tsig.key
      #     cloudflare:
      #       apiTokenSecretRef:
      #         name: cloudflare-issuer-secret
      #         key: CLOUDFLARE_DNS_TOKEN
      #   selector:
      #     dnsZones:
      #       - "lpo-lab.dev"
