---
defaultPodOptions:
  securityContext:
    fsGroup: 101
controllers:
  bind:
    replicas: 1
    containers:
      bind:
        image:
          repository: ubuntu/bind9
          tag: 9.18-22.04_beta@sha256:29378a263f22311f6a4f11fa9119182655244af17fca16a3e1993a3d0abe7abf
          pullPolicy: IfNotPresent
        resources:
          requests: {cpu: 50m, memory: 64Mi}
          limits: {memory: 256Mi}
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 5
        ports:
          - name: dns-tcp
            containerPort: 53
            protocol: TCP
          - name: dns-udp
            containerPort: 53
            protocol: UDP
            # volumeMounts:
            #   - name: named-conf
            #     mountPath: /etc/bind/named.conf
            #     subPath: named.conf
            #     readOnly: true
            #   - name: zone-file
            #     mountPath: /var/lib/bind/db.zone
            #     subPath: db.zone
            #     readOnly: false
            #   - name: tsig-key
            #     mountPath: /etc/bind/keys/tsig.key
            #     subPath: tsig.key
            #     readOnly: true
    pod:
      dnsPolicy: ClusterFirstWithHostNet # keep ClusterFirst if you don't use hostNetwork
      # hostNetwork: true   # <-- only if you prefer binding directly on node IPs

service:
  dns-tcp:
    controller: bind
    enabled: true
    type: LoadBalancer
    externalTrafficPolicy: Cluster
    annotations:
      lbipam.cilium.io/ips: "10.2.128.236"
      lbipam.cilium.io/sharing-key: "10.2.128.236"
    ports:
      dns-tcp:
        port: 53
        protocol: TCP
        targetPort: dns-tcp
  dns-udp:
    controller: bind
    enabled: true
    type: LoadBalancer
    externalTrafficPolicy: Cluster
    annotations:
      lbipam.cilium.io/ips: "10.2.128.236"
      lbipam.cilium.io/sharing-key: "10.2.128.236"
    ports:
      dns-udp:
        port: 53
        protocol: UDP
        targetPort: dns-udp

# No persistence (ephemeral zone)
persistence:
  named-conf:
    enabled: true
    type: configMap
    identifier: bind-named-conf
    globalMounts:
      - path: /etc/bind/named.conf
        subPath: named.conf
        readOnly: true
  db-zone:
    enabled: true
    type: configMap
    identifier: bind-zone
    globalMounts:
      - path: /var/lib/bind/db.zone
        subPath: db.zone
        readOnly: true
  tsig-key:
    enabled: true
    type: secret
    name: bind9-tsig
    globalMounts:
      - path: /etc/bind/keys/tsig.key
        subPath: tsig.key
        readOnly: true

# Ship BIND config and zone via ConfigMaps
configMaps:
  bind-named-conf:
    enabled: true
    data:
      named.conf: |
        options {
          directory "/var/lib/bind";
          recursion no;
          allow-query { any; };
          listen-on port 53 { any; };
          listen-on-v6 { none; };
          minimal-responses yes;
          rate-limit { responses-per-second 20; };

          check-names master ignore;
        };

        include "/etc/bind/keys/tsig.key";

        # TSIG-protected dynamic zone for ACME
        zone "_acme-challenge.lpo-lab.dev" {
          type master;
          file "/var/lib/bind/db.zone";
          update-policy {
            grant cm-acme zonesub txt;
          };
          allow-transfer { none; };
        };

  bind-zone:
    enabled: true
    data:
      db.zone: |
        $TTL 10
        @   IN SOA ns-acme01.lpo-lab.dev. hostmaster.lpo-lab.dev. (
                10       ; serial (bump)
                3600
                600
                604800
                10 )
            IN NS ns-acme01.lpo-lab.dev.
      # RBAC not needed; no sidecars
