---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/argoproj.io/applicationset_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: home-ops-apps
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=invalid"
  generators:
    - git:
        repoURL: https://github.com/zocimek/argocd-test.git
        revision: main
        files:
          - path: kubernetes/apps/*/app.yaml
  template:
    metadata:
      name: "{{ .name }}"
      namespace: argocd
    spec:
      destination:
        namespace: "{{ .namespace }}"
        server: https://kubernetes.default.svc
      project: default
  templatePatch: |-
    metadata:
      annotations:
        argocd.argoproj.io/appset: "true"
        {{- if .serverSideApply }}
        argocd.argoproj.io/compare-options: ServerSideDiff=true
        {{- end }}
        {{- range $k, $v := .annotations }}
        {{ $k }}: {{ $v }}
        {{- end }}
    spec:
      sources:
        {{- if .repoURL }}
        - repoURL: "{{ .repoURL }}"
          targetRevision: "{{ .chartVersion | default .version }}"
          chart: "{{ .chartName | default .name }}"
          helm:
            releaseName: "{{ .name }}"
            valueFiles:
            - $repo/kubernetes/apps/{{ .namespace }}/{{ .name }}/values.yaml
        {{- end }}
        {{- if .withKustomize }}
        - repoURL: {{ .repoURL | default "https://github.com/zocimek/argocd-test.git" }}
          targetRevision: {{ .version | default "staging" }}
          path: "{{ .repoPath }}"
          kustomize: {}
        {{- end }}
        - repoURL: https://github.com/zocimek/argocd-test.git
          path: kubernetes/apps
          targetRevision: main
          ref: repo
          directory:
            recurse: true
            include: '{{ .namespace }}/{{ .name }}/templates/*.yaml'
      syncPolicy:
        automated:
          prune: true
          {{- if .selfHeal }}
          selfHeal: true
          {{- end }}
        syncOptions:
          - CreateNamespace=true
          {{- if .serverSideApply }}
          - ServerSideApply=true
          {{- end }}
          {{- range $opt := .syncOptions }}
          - "{{ $opt }}"
          {{- end }}
        {{- with .retries }}
        retry:
          limit: {{ . }}
          backoff:
            duration: 10s
            factor: 1
        {{- end }}
      {{- if .ignoreDifferences }}
      ignoreDifferences:
        {{- .ignoreDifferences | nindent 4 }}
      {{- end }}
