---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: root-domain-tls
spec:
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: root-domain-tls
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: root-domain-tls/tls.crt
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: root-domain-tls/tls.key
