---
fullnameOverride: cloudflare-dns
provider:
  name: cloudflare
env:
  - name: &name CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: &secret cloudflare-dns-secret
        key: CLOUDFLARE_DNS_TOKEN
  - name: &name CF_ZONE_ID
    valueFrom:
      secretKeyRef:
        name: *secret
        key: CLOUDFLARE_ZONE_ID
extraArgs:
  - --cloudflare-dns-records-per-page=1000
  - --cloudflare-proxied=false
  - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
  - --crd-source-kind=DNSEndpoint
  - --gateway-name=envoy-internal,envoy-external
  - --zone-id-filter=$(CF_ZONE_ID)
triggerLoopOnEvent: true
policy: sync
sources:
  - crd
  - gateway-httproute
txtOwnerId: default
txtPrefix: k8s.
domainFilters:
  - lpo-lab.dev
serviceMonitor:
  enabled: true
podAnnotations:
  secret.reloader.stakater.com/reload: *secret
