apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden
spec:
  storageClassName: openebs-hostpath
  # dataSourceRef:
  #   kind: ReplicationDestination
  #   apiGroup: volsync.backube
  #   name: vaultwarden-dst
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
