---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/postgres-operator.crunchydata.com/postgrescluster_v1beta1.json
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: zabbix
  labels:
    crunchy-users.henrywhitaker3.github.com/watch: "true"
  annotations:
    crunchy-users.henrywhitaker3.github.com/superuser: "postgres"
spec:
  postgresVersion: 17
  monitoring:
    pgmonitor:
      exporter:
        resources:
          requests:
            cpu: 10m
            memory: 64M
          limits:
            memory: 512M
  patroni: # turn on sync writes to at least 1 other replica
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        max_wal_size: 5GB
        synchronous_commit: "on"
        parameters:
          max_connections: 500
        pg_hba:
          - hostnossl all all 10.42.0.0/16 md5
          - hostssl all all all md5
  instances:
    - name: postgres
      metadata:
        labels:
          app.kubernetes.io/name: zabbix-pg
      replicas: 2
      dataVolumeClaimSpec:
        storageClassName: openebs-hostpath
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 5Gi
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: "DoNotSchedule"
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: zabbix-pg
  users:
    # Superuser
    - name: "postgres"
      databases:
        - "postgres"
      options: "SUPERUSER"
      password:
        type: AlphaNumeric
    # Applications
    - name: zabbix
      databases:
        - zabbix
      password:
        type: AlphaNumeric

  proxy:
    pgBouncer:
      port: 5432
      config:
        global:
          pool_mode: session
          client_tls_sslmode: prefer
          default_pool_size: "100"
          max_client_conn: "500"
