apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://10.0.42.112:8200"
      path: "kubernetes"
      version: "v2"
      auth:
        # Authenticate against Vault using a Kubernetes ServiceAccount
        # token stored in a Secret.
        # https://www.vaultproject.io/docs/auth/kubernetes
        kubernetes:
          # Path where the Kubernetes authentication backend is mounted in Vault
          mountPath: "approle"
          # A required field containing the Vault Role to assume.
          roleId: "b765c6e7-77b9-3379-c3d1-8bb2ebd5a88f"
          # Optional secret field containing a Kubernetes ServiceAccount JWT
          #  used for authenticating with Vault
          secretRef:
            name: "vault-role-secret"
            key: "secret-id"
            namespace: "external-secrets"
