---
crds:
  enabled: true
dns01RecursiveNameservers: 10.2.128.236:53
dns01RecursiveNameserversOnly: true
prometheus:
  enabled: true
  servicemonitor:
    enabled: true
podDnsConfig:
  # ensure FQDNs are not expanded with search domains, so cilium can apply policies correctly
  options:
    - name: "ndots"
      value: "1"
containerSecurityContext: &csc
  readOnlyRootFilesystem: true
resources: &resources
  requests:
    cpu: "50m"
    memory: "32Mi"
  limits:
    memory: "512Mi"
webhook:
  containerSecurityContext: *csc
  replicaCount: 2
  resources: *resources
  podDisruptionBudget:
    enabled: true
cainjector:
  containerSecurityContext: *csc
  resources: *resources
startupapicheck:
  containerSecurityContext: *csc
  resources: *resources
