---
controllers:
  vaultwarden:
    annotations:
      reloader.stakater.com/auto: "true"
    pod:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    containers:
      app:
        image:
          repository: vaultwarden/server
          tag: 1.34.3@sha256:84fd8a47f58d79a1ad824c27be0a9492750c0fa5216b35c749863093bfa3c3d7
        env:
          DOMAIN: https://vaultwarden.lpo-lab.dev
          TZ: Europe/Warsaw
          SIGNUPS_ALLOWED: false
          WEBSOCKET_ENABLED: true
          SMTP_HOST: 10.0.42.108
          SMTP_PORT: 25
          SMTP_FROM: no-reply@pospiech.dev
          SMTP_SECURITY: "off"
        envFrom:
          - secretRef:
              name: vaultwarden-secret
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: {drop: ["ALL"]}
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            memory: 500Mi
service:
  app:
    ports:
      http:
        port: 80
route:
  app:
    hostnames:
      - vaultwarden.lpo-lab.dev
    parentRefs:
      - name: envoy-external
        namespace: network
persistence:
  data:
    existingClaim: vaultwarden
